version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: /bin/bash
    tty: true
    stdin_open: true

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users

volumes:
  postgres_data:
